/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.cell;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author alejo
 */
public class ActionPanel extends javax.swing.JPanel {

    /**
     * Creates new form ActionPanel
     */
    public ActionPanel() {
        initComponents();
    }
    
    public void initEvent(TableActionEvent event, int row){
    cmdReparacion.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent ae) {
               event.onRevision(row);
        }
        
    });
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acttionButton1 = new raven.cell.ActtionButton();
        acttionButton2 = new raven.cell.ActtionButton();
        acttionButton3 = new raven.cell.ActtionButton();
        acttionButton4 = new raven.cell.ActtionButton();
        acttionButton5 = new raven.cell.ActtionButton();
        cmdReparacion = new raven.cell.ActtionButton();

        cmdReparacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raven/cell/configuraciones (1).png"))); // NOI18N
        cmdReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdReparacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cmdReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdReparacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdReparacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven.cell.ActtionButton acttionButton1;
    private raven.cell.ActtionButton acttionButton2;
    private raven.cell.ActtionButton acttionButton3;
    private raven.cell.ActtionButton acttionButton4;
    private raven.cell.ActtionButton acttionButton5;
    private raven.cell.ActtionButton cmdReparacion;
    // End of variables declaration//GEN-END:variables
}
